### ISSUE TITLE
Enable a link from the Start-Menu to iSpector (Windows 10)

### ISSUE THREAD

**Issue by cpavanrun** [UiL-OTS-labs/iSpector#3]
Currently the installer creates a shortcut in the form of:
`Programs/UiL-OTS/iSpector-x.x.lnk`
I would recommend adding a link as such:
`Programs/iSpector-x.x.lnk`

This way the iSpector can be easily found under the start menu of the new Windows (10). Currently it's only visible under the `UiL-OTS` subfolder which has lead some user to think it's not installed.

**Comment by maartenuni** [comment]
I don't precisely know when this feature was added. In f608dfa2e82e42cad46f9e74d58f474a57c9eb39 it is most certainly fixed.
